/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_viatom_azur_tools_AdpcmDecoder */

#ifndef _Included_com_viatom_azur_tools_AdpcmDecoder
#define _Included_com_viatom_azur_tools_AdpcmDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_viatom_azur_tools_AdpcmDecoder
 * Method:    decodeAdpcm
 * Signature: ([C[C)I
 */
JNIEXPORT jint JNICALL Java_com_viatom_azur_tools_AdpcmDecoder_decodeAdpcm
  (JNIEnv *, jclass, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
